# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: all_in_one.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ll_in_one.proto\";\n\x05\x43ity1\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07zipCode\x18\x02 \x01(\x05\x12\x13\n\x0b\x63ountryName\x18\x03 \x01(\t\"3\n\x07Street1\x12\x12\n\nstreetName\x18\x01 \x01(\t\x12\x14\n\x04\x63ity\x18\x02 \x01(\x0b\x32\x06.City1\"S\n\tBuilding1\x12\x14\n\x0c\x62uildingName\x18\x01 \x01(\t\x12\x16\n\x0e\x62uildingNumber\x18\x02 \x01(\x05\x12\x18\n\x06street\x18\x03 \x01(\x0b\x32\x08.Street1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'all_in_one_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CITY1._serialized_start=20
  _CITY1._serialized_end=79
  _STREET1._serialized_start=81
  _STREET1._serialized_end=132
  _BUILDING1._serialized_start=134
  _BUILDING1._serialized_end=217
# @@protoc_insertion_point(module_scope)
